version: '3.9'

services:
  web:
    container_name: inputstudio.co
    image: ghcr.io/inputstudio/inputstudio.co:latest
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.inputstudio.rule=Host(`inputstudio.co`)'
      - 'traefik.http.routers.inputstudio.entrypoints=websecure'
      - 'traefik.http.routers.inputstudio.tls.certresolver=letsencryptresolver'

  directus:
    container_name: directus
    image: directus/directus:10
    restart: always
    volumes:
      - directus-uploads:/directus/uploads
    env_file:
      - stack.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.directus.rule=Host(`content.inputstudio.co`)"
      - "traefik.http.routers.directus.entrypoints=websecure"
      - "traefik.http.routers.directus.tls.certresolver=letsencryptresolver"

networks:
  default:
    name: internal-net
    external: true

volumes:
  directus-uploads:
    name: inputstudio-directus-uploads
