name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker image and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/inputstudio/inputstudio.co:latest
      - name: Trigger Portainer stack webhook
        run: curl -X POST ${{ secrets.PORTAINER_STACK_WEBHOOK }}
